project_name: gremlins
builds:
  - main: ./cmd/gremlins
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
source:
  enabled: true
changelog:
  skip: false
  use: github
  filters:
    exclude:
      - '^test:'
      - '^docs:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
release:
  draft: true
  prerelease: auto