before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/gremlins
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^docs:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
release:
  draft: true